### ISSUE TITLE
Seeding relationships

### ISSUE THREAD

**Issue by AngryUbuntuNerd** [heavenshell/py-sqlalchemy_seed#15]
Is it possible to seed relationships as well?

What I would like to do is this:
```yaml
- model: api.models.Business
  fields:
    name: Test Corp
    type: Limited
    addresses:
    - model: api.models.Address
      fields:
        street1: Test street 1
        street2: Test street 2
        city: London
        state: Greater London
        country: GB
```
Trying this currently leads to an Error: 

> TypeError: unhashable type: 'dict'

**Comment by heavenshell** [comment]
@AngryUbuntuNerd 
Nesting models are not supported, but you can describe like followings.
(Sorry I don't support nesting, it too complecated)

```
- model: api.models.Business
  id: 1
  fields:
    name: Test Corp
    type: Limited
    address_id: 1
```

```
- model: api.models.Address
  id: 1
  fields:
    street1: Test street 1
    street2: Test street 2
    city: London
    state: Greater London
    country: GB
```

See test file and tests directry.
https://github.com/heavenshell/py-sqlalchemy_seed/blob/master/tests/test_sqlalchey_seed.py#L36-L73
https://github.com/heavenshell/py-sqlalchemy_seed/tree/master/tests/fixtures
