### ISSUE TITLE
Id Value Not Used

### ISSUE THREAD

**Issue by crcornwell** [heavenshell/py-sqlalchemy_seed#55]
In the example fixture data, the format is:
```
- model: some.model.Name
   id: 1
   fields:
     foo: bar
```
However, it appears the the `id` field is never actually referenced in the code. I addressed this by moving my `id` field into the `fields` list, but I wonder if you'd prefer to deal with this in a different way?

I only mention it because I was going to add a test case for the "upsert" PR that I just introduced, but it wouldn't quite work with the existing test data since the primary keys were not being taken from the fixtures, but are instead being generated automatically on each insert.

**Comment by crcornwell** [comment]
I think an example might help clarify; I'll use your test data:
```
- model: tests.test_sqlalchey_seed.Account
  id: 1
  fields:
    first_name: John
    last_name: Lennon
    age: 20
- model: tests.test_sqlalchey_seed.Account
  id: 2
  fields:
    first_name: Paul
    last_name: McCartney
    age: 21
```
The account model is defined as:
```
class Account(Base):
    __tablename__ = 'accounts'

    id = Column(Integer, primary_key=True)
    first_name = Column(String(100), nullable=False)
    last_name = Column(String(100), nullable=False)
    age = Column(Integer(), nullable=True)

    def __repr__(self):
        """Repr."""
        return 'Account(id={0}, first_name={1}, last_name={2}, age={3})'.format(
            self.id, self.first_name, self.last_name, self.age,
        )
```
That defines the `id` column as the primary key for the `accounts` table. If we were to run `load_fixtures` with the fixtures above, everything would work fine. However, we can see that when the instances are defined (line 87 in `__init__.py`) it only references the `fields` key:
```
instance = model(**data['fields'])
```
This means that the `id` defined in the yaml fixture is being ignored, and the `id` is being set by the database during the insert query using the table's autoincrement. if we were to call `load_fixtures` again, the state of our `accounts` table would be:

|id|first_name|last_name|age|
|--|----------|----------|----|
|1|John|Lennon|20|
|2|Paul|McCartney|21|
|3|John|Lennon|20|
|4|Paul|McCartney|21|

I addressed this by moving the `id` into the `fields` list, e.g.:
```
- model: tests.test_sqlalchey_seed.Account
  fields:
    id: 1
    first_name: John
    last_name: Lennon
    age: 20
- model: tests.test_sqlalchey_seed.Account
  fields:
    id: 2
    first_name: Paul
    last_name: McCartney
    age: 21
```
This allows `load_fixtures` to insert using the `id` assigned in the fixture, and makes it an idempotent action.

**Comment by heavenshell** [comment]
@crcornwell Thx for comment.

I check behavior.
Yeah you can move `id` to `fields` if you want.
If you don't want to describe `id` at `fields`, it's ok.

User can choose describe `id` or not by his/her use cases.

## eg
main.py
```python
from sqlalchemy_seed import (
    create_table,
    load_fixtures,
    load_fixture_files,
)
from models import Base, session


def main():
    create_table(Base, session)

    path = './'
    fixtures = load_fixture_files(path, ['accounts.yaml'])
    print(fixtures)
    load_fixtures(session, fixtures)


if __name__ == '__main__':
    main()
```

accounts.yaml
```yml
- model: models.Account
  fields:
    first_name: John
    last_name: Lennon
    age: 20
- model: models.Account
  fields:
    first_name: Paul
    last_name: McCartney
    age: 21
```

```
$ python main.py
```

```
$ sqlite3 test.db
SQLite version 3.28.0 2019-04-16 19:49:53
Enter ".help" for usage hints.
sqlite> select * from accounts;
1|John|Lennon|20
2|Paul|McCartney|21
sqlite>
```

## Edit accounts.yaml
```yml
- model: models.Account
  fields:
    id: 1
    first_name: John
    last_name: Lennon
    age: 40
- model: models.Account
  fields:
    id: 2
    first_name: Paul
    last_name: McCartney
    age: 41
```
Edit `age` value.

```
python main.py
```

```
$ sqlite3 test.db
SQLite version 3.28.0 2019-04-16 19:49:53
Enter ".help" for usage hints.
sqlite> select * from accounts;
1|John|Lennon|40
2|Paul|McCartney|41
sqlite> 
```

It's better to add README.rst to something like `How to update existing seeds example`.
